### ISSUE TITLE
Don't use '*' instead of a version number in the package.json file 

### ISSUE THREAD

**Issue by JakubMrozek** [evernote/evernote-sdk-js#20]
This is the content of the package.json (https://github.com/evernote/evernote-sdk-js/blob/master/sample/express/package.json).

```
"dependencies": {
  "express": "3.1.0",
  "jade": "*",
  "less-middleware": "*",
  "evernote": "*"
  }
```

But your Express app example is compatible only with older version of jade and less-middleware and it doesn't work with the current version of these packages.

Also I think your sample codes (https://dev.evernote.com/doc/articles/creating_notes.php) works only with older version of evernote sdk.

Btw why you don't use unit tests? It is not a good idea to publish your code without tests...

**Comment by vargalas** [comment]
Interesting to see this really simple issue open after two years... 
and even the solution has been given here by @kyounger . But in the repo, you see the non-working sample. 
Quite a shame.
Trying to start an app wich works with Evernote, but this is not a good sign  👎

**Comment by akhaku** [comment]
Done
