### ISSUE TITLE
Bad response content type from "https://sandbox.evernote.com//edam/user": text/html

### ISSUE THREAD

**Issue by saveman71** [evernote/evernote-sdk-js#27]
Hello,

I'm using the node module (release `1.25.3`) and I'm getting the following error when I try to access something after oauth phase:
`'Bad response content type from "https://sandbox.evernote.com//edam/user": text/html'`

This also happens with the provided express sample.
### Steps to reproduce:

Launch the express sample, go to `http://localhost:3000/` and authorize your application (I'm using sandbox credentials of course).

You may have to adjust some code due to the use of wildcards the `package.json` that prevent the example to work properly out of the box.

When the authorization succeed, sadly the error is not handled by the express route, so here is the modified code that shows the error:

`~/evernote-sdk-js/sample/express/routes/index.js:16`

``` javascript
noteStore.listNotebooks(function(err, notebooks){
  console.log(err); // added debug
  req.session.notebooks = notebooks;
  res.render('index');
});
```

This will display the error when the oauth process is complete (or in any case if the token is already in the session):

`Bad response content type from "https://sandbox.evernote.com//edam/user": text/html`

It seems that `text/html` is sent by evernote instead of `application/x-thrift`, maybe it is what we get when going on https://sandbox.evernote.com//edam/user through the browser.

After some research, it is maybe related to [this](https://discussion.evernote.com/topic/27698-edamtest-php-userstore-failure/)

PS: It seems there is a (maybe) unrelated issue about the double `/` in the generated url

**Comment by mkustikova** [comment]
Hey @saveman71, I am experiencing a similar problem! Have you resolved it? noteStore.listNotebooks does not work for me for some reason

**Comment by saveman71** [comment]
@mkustikova Yes I found the solution! For me it was simply a network problem with our coworking space. I had to switch to a VPN when I was working on this, and it worked on my home connexion. 

Good luck
