### ISSUE TITLE
Timeline for CORS?

### ISSUE THREAD

**Issue by thejohnfreeman** [evernote/evernote-sdk-js#28]
The FAQ says Evernote CORS has "not yet" been implemented for some time now ([at least a 18 months](https://github.com/evernote/evernote-sdk-js/blob/c553376d238f8b72367c07e2274c5227b117a428/README.md)). Is it actually planned, or was that "not yet" overly optimistic?

**Comment by xypaul** [comment]
:+1:

**Comment by akhaku** [comment]
We don't have any immediate plans of supporting CORS - you'll have to go server-to-server.
