### ISSUE TITLE
CERT_UNTRUSTED when initializing Evernote Client in the node.js SDK

### ISSUE THREAD

**Issue by scorpwarp23** [evernote/evernote-sdk-js#32]
Hi, 

I'm getting the following error using the node client:

``` CERT_UNTRUSTED```

My code (coffeescript) is as follows:

```

```
client = new Evernote.Client(
  consumerKey: 'my consumer key'
  consumerSecret: 'my secret'
  sandbox: false
)

f = new Future()
client.getRequestToken(config_settings.private.evernote_callbackUrl+user_id,
(error, oauthToken, oauthTokenSecret, results) ->
  if error
    console.info("Error with Evernote OAuth:"+error)
    f['return'](false)
  else
    new Fiber(()->
      userDetails.update({user_id:user_id},{$set:{evernote_intermediate:{oauthToken: oauthToken,oauthTokenSecret: oauthTokenSecret}}})
    ).run()
    f['return'] (client.getAuthorizeUrl(oauthToken))
)
```

```

It appears the error is because www.evernote.com redirects to evernote.com causing as SSL error due to some mismatch.

By my reckoning the following code *(Lines 28-32)* of evernote-sdk-js/evernote/node/client.js is the culprit:

```

  if (this.sandbox) {
    var defaultServiceHost = 'sandbox.evernote.com';
  } else {
    var defaultServiceHost = 'www.evernote.com';
  }

```

```

**Comment by iosonofabio** [comment]
Bump, I have the same problem. I coded it using the Evernote JS SDK and get the same error, then recoded it using jsOAuth and it works, so I am really confused:

```coffeescript 
    # (the credentials are in sync.credentials)

    # step 1 (pure OAuth)
    # THIS WORKS!
    console.log 'EvernoteWindow before step 1'
    success = (data) ->
      console.log "success"
      vars = data.text.split "&"
      console.log(vars)
      console.log "success exit"
    failure = ->
      console.log 'error'
      console.log error
    options =
      consumerKey: sync.credentials.consumerKey
      consumerSecret: sync.credentials.consumerSecret
      callbackUrl : sync.callbackUrl
      signatureMethod : "HMAC-SHA1"
    oauth = OAuth options
    evernoteHostName = 'https://sandbox.evernote.com'
    oauth.request {'method': 'GET', 'url': evernoteHostName + '/oauth', 'success': success, 'failure': failure}

    # step 1 (evernote SDK)
    # THIS FAILS BY CERT_UNTRUSTED
    console.log 'EvernoteWindow before step 1 (SDK)'
    callbackGRT = (error, oauthToken, oauthTokenSecret, results) ->
      if error
        console.log "error"
        console.log error
      else
        console.log "success"
        console.log 'token' + oauthToken
        console.log 'secret' + oauthTokenSecret
        console.log 'results' + results
    client = new Evernote.Client sync.credentials
    client.getRequestToken sync.callbackUrl, callbackGRT

```
any clue?

**Comment by akhaku** [comment]
Odd, mind giving it a shot with v2.0.0-beta?
