### ISSUE TITLE
How to use app nootbook oauth?

### ISSUE THREAD

**Issue by zhaokun** [evernote/evernote-sdk-js#39]
there's no examples and i tried add `supportLinkedSandbox=true&suggestedNotebookName=myNotebook` in oauth url but dose no work.

**Comment by matthewayne** [comment]
App Notebooks are used on an API key/authentication level.  No change in the SDK is necessary for an App Notebook API key to work.  To change your API key from a Basic or Full access key to a basic or full access app notebook key open up a support ticket: https://dev.evernote.com/support

**Comment by zhaokun** [comment]
I tried, but failed all day. how "To change your API key from a Basic or Full access key to a basic or full access app notebook key"? please?  : ]

ps: I have a full access consumerKey and consumerSecret used in sandbox env.
