### ISSUE TITLE
getResourceRecognition returns a JSON data instead of .enex file.Issue with Javascript sdk

### ISSUE THREAD

**Issue by Christwin** [evernote/evernote-sdk-js#41]
We Used the below function to get the content of a JPEG.

noteStore.getResourceRecognition(authenticationToken,guidnum,function(notes){
       console.log('Success- ' + JSON.stringify(notes));
},function onerror(error) {
console.log('Error- ' + JSON.stringify(error));
});

It was given like the expected response would be in the form of an xml (.enex file) having the specifications of the texts present in the file.But what we got was in the form of JSON and not understandable.

Function Responce
"body":{"0":255,"1":216,"2":255,"3":224,"4":0,"5":16,"6":74,"7":70,"8":73,"9":70,"10":0,"11":1,"12":0,"13":1,"14":0,"15":96,"16":0,"17":96,"18":0,"19" ...............................................................................  goes a long way.

We just read through the javascript sdk and found that getResourceRecognition call a function send which has the following lines.
var h=new XMLHttpRequest;
h.responseType="arraybuffer";

for all other function we tried JSON was the expected response but for getResourceRecognition it had to be xml.
We just removed the line "h.responseType="arraybuffer";" and got the .enex file in the response of the request and viewed them in the logs (console.log(h.response)) though the output of the getResourceRecognition function was an error as we guess though might be wrong the other following functions expected arraybuffer.

Kindly help and guide us if we are in the wrong track.

Console Log Response:
06-06 08:14:25.539: D/CordovaLog(3172):
<!DOCTYPE recoIndex PUBLIC "SYSTEM" "http://xml.evernote....dtd"><recoIndexdocType="unknown" objType="image" objID="951f92deb34119b57c259519a89b9f41" engineVersion="6.6.33.0" recoType="service" lang="en" objWidth="497" objHeight="235">
<item x="26" y="8" w="74" h="14">
<t w="60">blog-EN.doc</t>
</item>
<item x="113" y="8" w="57" h="11">
<t w="79">Microsoft</t>
<t w="63">Mierosoft</t>

**Comment by tango42** [comment]
The returned value is a Uint8Array object that requires a conversion to a buffer first followed by a toString('utf8') conversion.
