### ISSUE TITLE
createBusinessNotebook() returns error even when successful

### ISSUE THREAD

**Issue by mattnorris** [evernote/evernote-sdk-js#43]
var Evernote = require('evernote').Evernote;
    ...
    var notebook = new Evernote.Notebook();
    notebook.name = 'Sample Business Notebook ' + new Date().getTime();
    client.createBusinessNotebook(notebook, function(err, createdNotebook) {
      console.log(err); 
      console.log(createdNotebook);
      ...

prints the following: 

    [ReferenceError: Evernote is not defined] 
    undefined
 
However, if I call `client.getBusinessNoteStore().listNotebooks()`, I see that the notebook has been created. However, it does not contain the `SharedNotebook` that should be automatically created with the `BusinessNotebook`. Instead, its JSON shows its `sharedNotebooks` as null: 
 
    ...
    sharedNotebooks: null,
    ...
 
Is this a problem with the SDK? Or am I missing some detail? 

I have documented the same issue on the Developer Forum: https://discussion.evernote.com/topic/85956-createbusinessnotebook-returns-error-even-when-successful/

**Comment by mattnorris** [comment]
Just checking in to see if there is any progress. If I can be of any help and provide more information, please let me know.

**Comment by install** [comment]
Hi Matt, sorry for the late response. I'll take a look

**Comment by install** [comment]
@mattnorris I believe I addressed your errors,
Please install version `evernote@1.25.801-beta` of the npm module and let me know if you are still getting errors.

**Comment by mattnorris** [comment]
@install That worked great. Thank you! 

I'm also sorry for the late response. Just got back from vacation.

**Comment by install** [comment]
Glad to hear.  I've added the change into version 1.25.81 of the npm module.
