### ISSUE TITLE
Node.js Streams for Resource API

### ISSUE THREAD

**Issue by cshum** [evernote/evernote-sdk-js#44]
When working with resources with `.getResource()` or `.createNote()`, `.updateNote()`, 
the full file contents must be loaded to memory, which is bad for a non blocking io system like Node.js. 

Node.js uses [Streams](https://nodejs.org/api/stream.html), so that only a chunk of content is loaded into memory when streaming files. Wonder if Resource API can implement Readable/Writeable streams like:

``` js
noteStore.getResourceStream({ guid: ... })
  .pipe(fs.createWriteStream('./foo'));

var resource = new Evernote.Resource();
resource.data = fs.createReadStream('./bar');
```

**Comment by MichalCz** [comment]
Hi,

I'd help with this one if you're interested - but I'm not sure if evernote-sdk is still being developed...
