### ISSUE TITLE
how to use evernote js sdk in react-native

### ISSUE THREAD

**Issue by ChitaGideon** [evernote/evernote-sdk-js#47]
react-native use  Common js modules .
but react-native do not have some libs  can be used in nodejs
i.e.  fs  vm  path  crypto

how can I use evernote js sdk in commonjs way ,without the nodejs libs

**Comment by SaintEmbers** [comment]
Did you make any headway on this?

**Comment by ChitaGideon** [comment]
@SaintEmbers I give up  using  nodejs sdk in the client side.

**Comment by akhaku** [comment]
Yeah, apart from the libraries, the other issue you may have to deal with is cross-domain requests. You'd be better off setting up a server to proxy API requests.
