### ISSUE TITLE
Cannot read property byteLength of undefined in getUser

### ISSUE THREAD

**Issue by Cosrnos** [evernote/evernote-sdk-js#51]
We've recently upgraded out platform to Node 4.2.3 and have had some troubles from within the Evernote node Library.

Basically I've been digging into the following stack on a getUser call:

<img width="724" alt="all_apps_ _papertrail" src="https://cloud.githubusercontent.com/assets/5360729/11852727/4158e956-a3ff-11e5-88f1-e0add0627240.png">

It looks like something is happening within the Thrift library causing the returned ArrayBuffer from writeString to be undefined. The weird part is this is only happening on our servers and I can't seem to reproduce this locally. Wondering if anyone else has experienced this or knows the source of the issue.

I also noticed the thrift library being used is 3 patch versions behind (current: 0.9.0, latest: 0.9.3). That could possibly have a fix for this issue.

**Comment by akhaku** [comment]
Just release v2.0.0-beta, give that a shot? Thanks
