### ISSUE TITLE
Would evernote provide a new API to do user authorization in backend?

### ISSUE THREAD

**Issue by ervinewell** [evernote/evernote-sdk-js#61]
In some situations when I work, I want to get my notes from Evernote and show them in my own blog for my readers, so I have authorize my account in backend to get the OAUTHVERIFY key instead of redirecting to authorization page to fill in the form. Would evernote be able to provide such an API?

**Comment by akhaku** [comment]
It sounds like you want a developer token - see [this page](https://dev.evernote.com/doc/articles/dev_tokens.php) for more information on them.

**Comment by ervinewell** [comment]
Thanks a lot! This is what I want !
