### ISSUE TITLE
getNoteWithResultSpec is not implemented

### ISSUE THREAD

**Issue by leonkyr** [evernote/evernote-sdk-js#62]
Hello guys,

Following this [guid](https://dev.evernote.com/doc/reference/NoteStore.html#Fn_NoteStore_getNote) I should use getNoteWithResultSpec, which seems like not implemented in JavaScript SDK. 

Additionally, is it super time consuming to find how to create types necessary for API calls. I have to work with this file... https://github.com/evernote/evernote-sdk-js/blob/master/evernote-sdk-js/generated/NoteStore.js

Regards,
Leo

**Comment by akhaku** [comment]
Yeah sorry, we're in the process of updating our SDK to an all-new version. It's not complete yet, haven't had time to work on it recently - you can see the work-in-progress at https://github.com/akhaku/evernote-sdk-js

**Comment by leonkyr** [comment]
When do you expect to have it released @akhaku ?

**Comment by akhaku** [comment]
I don't think I have time to work on it this weekend, hopefully next weekend?

**Comment by alexisargyris** [comment]
Hi,

Any news regarding this function?

**Comment by akhaku** [comment]
Not at the moment, sorry - other things have taken priority over this. For the moment you can use my fork; it works, the main thing left is to update the documentation.

**Comment by alexisargyris** [comment]
ok, thanks, I'll give it a try.

**Comment by akhaku** [comment]
@alexisargyris did you run into any problems? Apart from the fact that the README hasn't been updated...

**Comment by akhaku** [comment]
@leonkyr and @alexisargyris, just realeased 2.0.0-beta. Let me know how it goes? 2.0.0-beta has getNoteWithResultSpec, among other cool features, see the README.

**Comment by leonkyr** [comment]
Thanks @akhaku I am on another project at the moment, so don't know whether will continue with Evernote

**Comment by alexisargyris** [comment]
@akhaku it works fine (and sorry for the long delay)
