### ISSUE TITLE
NoteFilter() and NotesMetadataResultSpec() no longer constructors

### ISSUE THREAD

**Issue by tjstalcup** [evernote/evernote-sdk-js#64]
Multiple SO questions dating from 2015 show using the JS SDK in this fasion:

```
filter = new Evernote.NoteFilter();
//set the notebook guid filter to the GUID of the default notebook
filter.notebookGuid = notebooks[0].guid; //change this to the GUID of the notebook you want
//create a new result spec for findNotesMetadata
resultSpec = new Evernote.NotesMetadataResultSpec();
//set the result spec to include titles
resultSpec.includeTitle=true;
```

The problem is it appears the API has changed recently in that neither of these constructors exist, resulting in the error below:

Evernote.NoteFilter is not a constructor

**Comment by akhaku** [comment]
Yup, the API changed with 2.0. Now when you require 'evernote', you get an object with a handle to a "client" (see the examples), [Errors](https://dev.evernote.com/doc/reference/Errors.html), [Limits](https://dev.evernote.com/doc/reference/Limits.html), [NoteStore](https://dev.evernote.com/doc/reference/NoteStore.html) (data types, not the service), [Types](https://dev.evernote.com/doc/reference/Types.html), and [UserStore](https://dev.evernote.com/doc/reference/UserStore.html) (data types, not the service).

Sounds like we need some help with documentation. Do you have time for a PR? Or I might have time next weekend.

**Comment by mariecl** [comment]
Not sure if that's great practice, but I ended up going for a solution where I create empty objects then manually populate each field as listed in the relevant data type found in the docs.
Example:

```
const noteStore = self.client.evernote().getNoteStore();
const filter = {};
filter.words = ['one', 'two', 'three'];
filter.ascending = true;
[...]

const offset = 'offset';

const spec = {};
spec.includeTitle = true;
spec.includeContentLength = true;
[...]   

noteStore.findNotesMetadata(filter, offset, self.maxNotes, spec, (error, data) => {
  [...]
};
```

**Comment by akhaku** [comment]
@mariecl that will work, technically. The "right" thing to do is to construct the objects with your fields (untested):

```
import Evernote from 'evernote';
const filter = new Evernote.NoteStore.NoteFilter({
    words: ['one', 'two', 'three'],
    ascending: true, // etc
});

```
We just need someone to update documentation...

**Comment by mariecl** [comment]
I've tested your suggestion @akhaku and it actually doesn't work.

```
const Evernote = require('evernote');
const filter = new Evernote.NoteFilter({
    words: ['one', 'two', 'three'],
    ascending: true,
    inactive: false,
});
console.log(filter)
// NoteFilter {}
```

This works though (but it's kind of a cheat):
```
const Evernote = require('evernote');
const filter = new Evernote.NoteFilter({});
filter.words = ['one', 'two', 'three'];
filter.inactive = false;
filter.ascending = true;
console.log(filter)
// NoteFilter {
//  words: [ 'one', 'two', 'three' ],
//  inactive: false,
//  ascending: true }
```

**Comment by akhaku** [comment]
What version of the API are you using? `new Evernote.NoteFilter({}) will no longer work with 2.0.

**Comment by mariecl** [comment]
I am using `2.0.1-beta`.

**Comment by akhaku** [comment]
That doesn't make sense - maybe you have an older version cached somewhere? I just tested my snippet above (using require instead of import) and it seems to work.
```
var Evernote = require('evernote');
console.log(new Evernote.NoteStore.NoteFilter({
    words: ['one', 'two', 'three'],
    ascending: true
}))
// output
{ words: [ 'one', 'two', 'three' ],
  ascending: true,
  order: null,
  notebookGuid: null,
  tagGuids: null,
  timeZone: null,
  inactive: null,
  emphasized: null,
  includeAllReadableNotebooks: null }
```

**Comment by mariecl** [comment]
I have checked my cache and re-installed the node modules from scratch. I am using the right version.

However, there are two differences between your sample and the way I run my code:
- you use `new Evernote.NoteStore.NoteFilter()` while I was using `new Evernote.NoteFilter({})`, so we're actually not testing the same thing :)
- the way I run my code was actually not as simple as the sample I gave you. I am actually running something like this:
```
module.exports = function(options) {
  const self =  {};
  
  self.evernoteLib = require('evernote'); // 1

  self.getEvents = function(options, cb) {
    // 2
    console.log(new self.evernoteLib.NoteStore.NoteFilter({
      words: ['one', 'two', 'three'],
      ascending: true
    }));
  };
}
```
In my actual sample, I am getting that error `TypeError: Cannot read property 'NoteFilter' of undefined`.
If I log the content of `self.evernoteLib` right after it's been required (location `//1`), and inside getEvents (location `//2`), I get completely different results:
- at location `//1`: I get the full Evernote library (about 100-200 keys)
- at location `//2`: I get ```{ NoteFilter: [Function: NoteFilter], NotesMetadataResultSpec: [Function: NotesMetadataResultSpec] }```

If I require Evernote from my getEvents function, the problem gets solved and your code runs fine. So I am guessing I am actually facing a scoping problem.

**Comment by mariecl** [comment]
@akhaku Is the above expected?

**Comment by akhaku** [comment]
I'm guessing you're doing something funky where it comes to requiring that module, or maybe (accidentally?) reassigning self.evernoteLib somewhere? I tried running a variation of your code (returned self from that module, required from another module) and everything worked okay, I got my NoteFilter out as expected. evernoteLib should only have a few keys - this is what I get when I run Object.keys(evernoteLib):
`[ 'Client', 'Errors', 'Limits', 'NoteStore', 'Types', 'UserStore' ]`

**Comment by mariecl** [comment]
I figured it out. Your solution works perfectly fine.

```
const filter = new require('evernote').NoteStore.NoteFilter({
  words: ['one', 'two', 'three'],
  ascending: true,
});
```

or in my case:

```
const filter = new self.evernoteLib.NoteStore.NoteFilter({
  words: ['one', 'two', 'three'],
  ascending: true,
});
```
is the way to go.

Like you said:
>  I'm guessing you're doing something funky where it comes to requiring that module, or maybe (accidentally?) reassigning self.evernoteLib somewhere?

The test I was using to run that code actually had a few lines overwriting `self.evernoteLib`...
I'll try to work on a PR to update the docs over the week-end.

Thanks for your help!
