### ISSUE TITLE
Outdated docs in Evernote Developers portal page 

### ISSUE THREAD

**Issue by dukewan** [evernote/evernote-sdk-js#68]
The code examples of Node.js SDK are outdated at Evernote Developers portal page which are very confusing.
<img width="664" alt="jietu20170219-220410" src="https://cloud.githubusercontent.com/assets/2100515/23113786/5e15d308-f6ef-11e6-9ccb-2f9e0e5a4ca1.png">

**Comment by renatomattos2912** [comment]
Really outdated, to make the code above work, some changes need to be made, like this:

1) Now the sdk uses Promises, so the portion of code needs to be like:

```
noteStore.createNote(ourNote)
.then(note => {
   console.log(note);
})
.catch(err => {
     thrown err
})
```

2) The new Evernote.Note() is not a valid constructor anymore, so i solved this calling new Evernote.Types.Note()

**Comment by akhaku** [comment]
Fixed
