### ISSUE TITLE
errorCode: 8, "authenticationToken"

### ISSUE THREAD

**Issue by mikestopcontinues** [evernote/evernote-sdk-js#75]
I just created a developer token, but with the following code, I'm getting this error:

```typescript
ThriftException {
    errorCode: 8,
    message: 'authenticationToken',
    rateLimitDuration: null 
}
```

What am I doing wrong?

```javascript
const client = new Evernote.Client({
  token: evernoteToken,
});

const noteStore = client.getNoteStore();

const newestFilter = new Evernote.NoteStore.NoteFilter({
  order: 2,
  ascending: false,
  inactive: false,
  includeAllReadableNotebooks: false,
});

const completeSpec = new Evernote.NoteStore.NotesMetadataResultSpec({
  includeTitle: true,
  includeContentLength: true,
  includeCreated: true,
  includeUpdated: true,
  includeDeleted: true,
  includeUpdateSequenceNum: true,
  includeNotebookGuid: true,
  includeTagGuids: true,
  includeAttributes: true,
  includeLargestResourceMime: true,
  includeLargestResourceSize: true,
});

noteStore.findNotesMetadata(newestFilter, 0, 10, completeSpec)
.then((data) => {
  console.log(data);
})
.catch(failed);
```

**Comment by galtenberg** [comment]
Make sure your token was created with full access requested.

**Comment by mikestopcontinues** [comment]
You don't get to choose with a token. I regenerated just to check. Same results.

**Comment by akhaku** [comment]
Assuming you created a developer token for production, make sure you pass in `false` for the `sandbox` option in the object passed to the `Evernote.Client` constructor.

**Comment by mikestopcontinues** [comment]
Fantastic! I must have totally missed that in the docs. Thanks!

**Comment by akhaku** [comment]
Yeah... it's there but really easy to miss, search for the word "production" in the README. Feel free to submit a PR to make it a bit more obvious :)

**Comment by routecueadi** [comment]
I'm getting the same error, but I changed `true` to `false` for sandbox everywhere. What else could cause it?
