### ISSUE TITLE
Unable to use 'getSharedNoteStore' can't get property sharedToken of undefined

### ISSUE THREAD

**Issue by adlb** [evernote/evernote-sdk-js#77]
When I try to use the simple sample from the readme about "NoteStore for linked notebooks", I have this error : Cannot read property 'sharedToken' of undefined.

Having a look to the code, it seems that the cache check is not robust enough:
```javascript
  const cache = this[linkedNotebook.sharedNotebookGlobalId];
  if (cache.sharedToken) {
    return Promise.resolve({token: cache.sharedToken, url: linkedNotebook.noteStoreUrl});
  } else {
    ... ...
  }
```

I guess we should check that cache is defined:
```javascript
  if (cache && cache.sharedToken)
```

regards

**Comment by akhaku** [comment]
That sounds accurate - PR welcome :)
