### ISSUE TITLE
how to add NoteSortOrder to filter?

### ISSUE THREAD

**Issue by kurokirasama** [evernote/evernote-sdk-js#86]
Which are the types of NoteSortOrder we can add to a filter and how? maybe like this:

```
const nFilter = new Evernote.NoteStore.NoteFilter({
  words: "searchQuery",
  NoteSortOrder: "magic?"
});
```

**Comment by akhaku** [comment]
I'd recommend digging through https://dev.evernote.com/doc/reference/. In particular, https://dev.evernote.com/doc/reference/Types.html#Enum_NoteSortOrder
