### ISSUE TITLE
How to solve self-signed certificate error

### ISSUE THREAD

**Issue by michalyao** [evernote/evernote-sdk-js#87]
I use evernote-sdk-js develop a vscode extension for evernote. One of my user encountered problem under corporate environment. It seems like that extension proxy is not supported in vscode.

 How can I solve this problem? Did I lose any configuration? See more detail at https://github.com/michalyao/evermonkey/issues/109.

**Comment by iafan** [comment]
@michalyao are you trying to connect to Evernote API directly from the JS code running on a Node.js-based client (Electron/VSCode)? You can look at [BinaryHTTPTransport](https://github.com/evernote/evernote-sdk-js/blob/master/src/thrift/transport/binaryHttpTransport.js) source code which uses [https](https://nodejs.org/api/https.html) module to see how the transport layer is implemented.

So you need to figure out how to bypass self-signed certificate issues in Node.js. A quick search gave me these two articles that might be relevant:
1. https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request
2. https://stackoverflow.com/questions/19665863/how-do-i-use-a-self-signed-certificate-for-a-https-node-js-server

**Comment by iafan** [comment]
According to https://github.com/michalyao/evermonkey/issues/109#issuecomment-376812524 you seem to have solved the issue, so I'm closing this question as solved.
